--------------------------------------------------------------------------------
-- Weight ROM Module
-- Dual-port ROM for storing CNN weights
-- Initialized from .mif files generated by extract_weights.py
--
-- This is a wrapper - actual ROM will be Quartus ALTSYNCRAM megafunction
-- For now, use simple array-based ROM
--
-- Author: Marly Capstone
-- Date: March 2026
--------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity weight_rom is
    generic (
        DATA_WIDTH : integer := 16;
        ADDR_WIDTH : integer := 14;  -- 2^14 = 16K locations
        INIT_FILE  : string := "weights.mif"
    );
    port (
        clk     : in  std_logic;

        -- Port A
        addr_a  : in  integer range 0 to 2**ADDR_WIDTH-1;
        data_a  : out signed(DATA_WIDTH-1 downto 0);

        -- Port B (optional second port for parallel access)
        addr_b  : in  integer range 0 to 2**ADDR_WIDTH-1;
        data_b  : out signed(DATA_WIDTH-1 downto 0)
    );
end weight_rom;

architecture Behavioral of weight_rom is

    -- ROM storage type
    type rom_type is array (0 to 2**ADDR_WIDTH-1) of signed(DATA_WIDTH-1 downto 0);

    -- Initialize ROM (will be replaced with .mif file in Quartus synthesis)
    signal rom_data : rom_type := (others => (others => '0'));

    -- Quartus attribute to specify initialization file
    attribute ram_init_file : string;
    attribute ram_init_file of rom_data : signal is INIT_FILE;

begin

    -- Dual-port read process
    process(clk)
    begin
        if rising_edge(clk) then
            data_a <= rom_data(addr_a);
            data_b <= rom_data(addr_b);
        end if;
    end process;

end Behavioral;
