--------------------------------------------------------------------------------
-- JTAG UART Bridge
-- Connects Altera JTAG UART IP to our uart_receiver interface
--
-- Uses USB-Blaster cable for UART communication (no extra hardware needed!)
-- Compatible with Python serial scripts
--
-- Author: Marly Capstone
-- Date: March 2026
--------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity jtag_uart_bridge is
    port (
        clk             : in  std_logic;
        reset_n         : in  std_logic;

        -- Output to our system (same interface as uart_receiver)
        ecg_sample      : out std_logic_vector(11 downto 0);
        sample_valid    : out std_logic;
        uart_active     : out std_logic;
        uart_error      : out std_logic
    );
end jtag_uart_bridge;

architecture Behavioral of jtag_uart_bridge is

    -- JTAG UART IP component (will be generated by Platform Designer)
    component jtag_uart_0
        port (
            clk             : in  std_logic;
            rst_n           : in  std_logic;
            av_chipselect   : in  std_logic;
            av_address      : in  std_logic;
            av_read_n       : in  std_logic;
            av_write_n      : in  std_logic;
            av_writedata    : in  std_logic_vector(31 downto 0);
            av_readdata     : out std_logic_vector(31 downto 0);
            av_waitrequest  : out std_logic;
            dataavailable   : out std_logic;
            readyfordata    : out std_logic;
            irq             : out std_logic
        );
    end component;

    -- Avalon MM signals
    signal av_chipselect   : std_logic := '1';
    signal av_address      : std_logic := '0';
    signal av_read_n       : std_logic := '1';
    signal av_write_n      : std_logic := '1';
    signal av_writedata    : std_logic_vector(31 downto 0) := (others => '0');
    signal av_readdata     : std_logic_vector(31 downto 0);
    signal av_waitrequest  : std_logic;
    signal dataavailable   : std_logic;
    signal readyfordata    : std_logic;

    -- State machine for reading bytes
    type state_type is (IDLE, CHECK_DATA, READ_BYTE1, READ_BYTE2, OUTPUT_SAMPLE);
    signal state : state_type := IDLE;

    signal byte_buffer : std_logic_vector(7 downto 0);
    signal byte_count  : integer range 0 to 1 := 0;
    signal sample_reg  : std_logic_vector(11 downto 0);

begin

    -- Instantiate JTAG UART IP
    jtag_uart_inst : jtag_uart_0
        port map (
            clk            => clk,
            rst_n          => reset_n,
            av_chipselect  => av_chipselect,
            av_address     => av_address,
            av_read_n      => av_read_n,
            av_write_n     => av_write_n,
            av_writedata   => av_writedata,
            av_readdata    => av_readdata,
            av_waitrequest => av_waitrequest,
            dataavailable  => dataavailable,
            readyfordata   => readyfordata,
            irq            => open
        );

    -- Read bytes and assemble 12-bit samples
    process(clk, reset_n)
    begin
        if reset_n = '0' then
            state <= IDLE;
            sample_valid <= '0';
            uart_active <= '0';
            uart_error <= '0';
            av_read_n <= '1';

        elsif rising_edge(clk) then

            sample_valid <= '0';
            av_read_n <= '1';

            case state is

                when IDLE =>
                    if dataavailable = '1' then
                        uart_active <= '1';
                        state <= READ_BYTE1;
                        av_read_n <= '0';  -- Start read
                    else
                        uart_active <= '0';
                    end if;

                when READ_BYTE1 =>
                    if av_waitrequest = '0' then
                        byte_buffer <= av_readdata(7 downto 0);  -- Lower 8 bits
                        state <= CHECK_DATA;
                    end if;

                when CHECK_DATA =>
                    if dataavailable = '1' then
                        state <= READ_BYTE2;
                        av_read_n <= '0';
                    else
                        state <= IDLE;  -- Wait for second byte
                    end if;

                when READ_BYTE2 =>
                    if av_waitrequest = '0' then
                        sample_reg <= av_readdata(3 downto 0) & byte_buffer;  -- Upper 4 + lower 8
                        state <= OUTPUT_SAMPLE;
                    end if;

                when OUTPUT_SAMPLE =>
                    ecg_sample <= sample_reg;
                    sample_valid <= '1';
                    state <= IDLE;

                when others =>
                    state <= IDLE;

            end case;

        end if;
    end process;

end Behavioral;
